name: waffarha_challenge
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  logger: ^1.3.0
  flutter_bloc: ^8.1.2
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.2.3
  get_it: ^7.6.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
